import React from 'react'

        const sources = [
            "A group of merchants talk about someone's disappearance. They mention a ",
            "A leather-bound diary is found in the wilds. The last entry is a hastily scribbled note about a ",
            "A seemingly senile elder wanders around town muttering of a ",
            "Etched into a stone is the warning of a ",
            "In order to frighten their children, locals tell an old tale of a ",
            "In the corner of the taverns sits a group of folk, pale and shaking, whispering wretchedly about a ",
            "In the hand of a withered corpse found along the roadside is a map with a drawing of a ",
            "Legend speaks of a ",
            "Nailed to a tree is a small note with a warning to all about a ",
            "Rumors speak of a ",
        ];

        const adjectives = [
            "blighted ",
            "cursed ",
            "dark ",
            "enchanted ",
            "fiery ",
            "floating ",
            "ghostly ",
            "growling ",
            "haunted ",
            "hidden ",
            "living ",
            "mercurial ",
            "mysterious ",
            "overgrown ",
            "ruined ",
            "seemingly ordinary ",
            "singing ",
            "sinister ",
            "strange ",
            "strangely alluring ",
            "sunken ",
            "treacherous ",
            "unfinished ",
        ];

        const places =  [
            "airship, ",
            "amphitheater, ",
            "archway, ",
            "area, ",
            "barracks, ",
            "basement, ",
            "cottage, ",
            "bridge, ",
            "cairn, ",
            "caravan, ",
            "carnival, ",
            "castle, ",
            "catacomb, ",
            "causeway, ",
            "cavern, ",
            "chapel, ",
            "citadel, ",
            "city block, ",
            "clock tower, ",
            "colossus, ",
            "community, ",
            "compound, ",
            "construction site, ",
            "crevasse, ",
            "crossroads, ",
            "den, ",
            "doorway, ",
            "dwelling, ",
            "estate, ",
            "field, ",
            "fishers hut, ",
            "fort, ",
            "fortress, ",
            "garden, ",
            "gate, ",
            "gazebo, ",
            "granary, ",
            "gravestone, ",
            "graveyard, ",
            "greenhouse, ",
            "grotto, ",
            "guard house, ",
            "hamlet, ",
            "hedge maze, ",
            "holy site, ",
            "hospital, ",
            "hotel, ",
            "house, ",
            "hut, ",
            "inn, ",
            "keep, ",
            "kennel, ",
            "lair, ", 
            "lighthouse, ",
            "lodge, ",
            "log cabin, ",
            "lumber camp, ",
            "manor, ",
            "mansion, ",
            "marketsplace, ",
            "mausoleum, ",
            "mine, ",
            "monestary, ",
            "monolith, ",
            "monument, ",
            "mural, ",
            "museum, ",
            "obelisk, ",
            "observatory, ",
            "orchard, ",
            "orphanage, ",
            "ossuary, ",
            "palace, ",
            "park, ",
            "pavilion, ",
            "pit, ",
            "prison, ",
            "property, ",
            "quarry, ",
            "sanctuary, ",
            "settlement, ",
            "shed, ",
            "ship, ",
            "shop, ",
            "shrine, ",
            "stable, ",
            "statue, ",
            "stronghold, ",
            "tavern, ",
            "temple, ",
            "tomb, ",
            "tower, ",
            "townhouse, ",
            "township, ",
            "treehouse, ",
            "tree, ",
            "tunnel, ",
            "villa, ",
            "wall, ",
            "warehouse, ",
            "way station, ",
            "windmill, ",
            "workshop, ",
        ];

        const descriptors = [
            "long-forgotten, ",
            "long-abandoned, ",
            "marked by the presence of a terrible beast, ",
            "strewn with the remnants of a terrible battle, ",
            "covered in etchings of a dark ritual, ",
            "glowing with an aura of silvery light, ",
            "said to be owned by an elderly mage, ",
            "said to be the site of a terrible crime, ",
            "said to be the site of a spell going terribly wrong, ",
            "letting off the feeling of a strange presence, ",
            "carved with runes or symbols like none have ever seen, ",
            "said to be home to evil spirits, ",
            "said to be corrupted by dark forces, ",
            "said to house something truly abnormal, ",
            "said to hold a cursed item, ",
            "said to be host to a masked ball at the solstice moons, ",
            "said to be a fabulous place to visit, ",
            "said to be a place of madness, ",
            "covered in eldritch symbols, ",
            "said to be place from where no one ever returns, ",
        ];

        const areas = [
            "along the coast... ",
            "along the road... ",
            "below the mountain... ",
            "beside the lake... ",
            "deep in the forest... ",
            "down in the swamp... ",
            "far away... ",
            "far out in the desert... ",
            "high in the mountain... ",
            "in a nearby cave... ",
            "in a place unknown... ",
            "in the neighboring nation... ",
            "near the outpost... ",
            "not far from town... ",
            "on a magical plane... ",
            "somewhere in the ocean... ",
            "somewhere in the wilderness... ",
            "somewhere on the great plains... ",
            "somewhere within the city walls... ",
            "underneath the city... ",
        ];

        const situations = [
            "It is definitely just a myth and you shouldn't worry. ",
            "Some dark magic seems to permeate the land around it. ",
            "There was some kind of horrible disaster there. ",
            "People who have seen it are not the same. ",
            "It drives you to insanity. ",
            "Something bad lives there. Some... thing... ",
            "There is nothing to see there, but a graveyard. ",
            "It turns people homicidal. ",
            "It's just a silly legend told to mess with outsiders. It's nothing, really. No really! ",
            "It is also said to hold great treasure. ",
            "People who have seen it start rambling in a strange language. ",
            "It should be avoided at all cost. ",
            "A strange fellow was also asking everyone about it, not too long ago. ",
            "A merchant's caravan was heading in its direction, and they never arrived at their final destination. ",
            "A group of adventurers went there a few days ago and have not been seen since. ",
            "The town idiot returned from there and said it is really is not as bad as people say it is. For some reason however, ",
        ];

        const persons = [
            "A child of the local farmer ",
            "A collector of sorts ",
            "A courtier of the local lord ",
            "A failed local artist ",
            "A famous artist ",
            "A hooded stranger ",
            "A loan shark ",
            "A local beggar ",
            "A local mason ",
            "A local noble ",
            "A local shopkeeper ",
            "A mysterious wanderer ",
            "A passing traveler ",
            "A peddler ",
            "A priest at a local temple ",
            "A stranger at the inn ",
            "A stranger whose name is always forgotten ",
            "A traveling merchant ",
            "A visiting noble; ",
            "A worried local craftsman ",
            "An interested archivist ",
            "An old friend of one of the adventurers ",
            "An old tinkerer ",
            "Another adventurer ",
            "The archivist ",
            "The bartender ",
            "The blacksmith ",
            "The captain of the guard ",
            "The child ",
            "The gravedigger ",
            "The herbalist ",
            "The librarian ",
            "The local ruler ",
            "The parent of a missing child ",
            "The sheepherder ",
            "The town wisdom ",
        ];

        const actions = [
                " starts crying when asked about the place.",
                " asks if the adventurers would accompany them there.",
                " asks the players to go explore.",
                " asks the players to destroy it.",
                " asks the players to collect something from it.",
                " asks for a souvenir from there.",
                " invites the players to a party, when asked about the place.",
                " faints, when asked about the place.",
                " suddenly disappears, when asked about the place.",
                " starts growling, when asked about the place.",
                " calls the guard, when asked about the place.",
                " hushes the adventurers, then leads them to their home, when asked about the place.",
                " tries to kill the players in their sleep.",
                " is seen with a map leading there.",
                " tries to rally people on the street to go there together for some reason.",
                " has covered all the walls of their house with drawings of the place.",
                " starts drooling when asked about the place.",
                " freezes for a second before completely ignoring the adventurers and walking away, when asked about the place.",
                " starts singing and dancing wildly, when asked about the place.",
                " says it is already too late.",
        ];


export const Rumor = ( {data} ) => {


    function Rumor() {
        function randomize(input) {
            let random = Math.floor(Math.random() * input.length);
            return input[random];
        }
        let theRumor = randomize(sources) + randomize(adjectives) + randomize(places) + randomize(descriptors) + randomize(areas) + '  If you investigate further, you are later told that: ' + randomize(situations) + randomize(persons) + randomize(actions);

        return theRumor; 
    }
  
  
  
  
  
  return (

        <main className="main my-3">
         { Rumor() }
        </main>
        
  )
}

export default Rumor